Update MT_dataset.py (#3218)
change anno_output_path to "annos" instead of "anno".

1. copy the code snippet in the readme and execute it :
python3 tools/convert_tools/convert_mask_to_coco.py --image_path dataset/MT_dataset/images/train --anno_path dataset/MT_dataset/annos/train --class_num 5 --label_file dataset/MT_dataset/mt_catIDs.json --output_name dataset/MT_dataset/train.json --suffix .png

2. there is a exception:
FileNotFoundError: dataset/MT_dataset/annos/train/exp1_num_108719.png is not found.

3. the root cause is the "anno" and "annos" are not consistent in the docs and code.

to align with "images", the "anno" should be "annos"